### ISSUE TITLE
Directory Index + Alias overlap

### ISSUE THREAD

**Issue by Tuckie** [Octo-Labs/middleman-alias#11]
I currently have a file named contact.html & have directory indexes turned on.

In order to map over from my old site's URL, I've added 'alias: contact.html' to the frontmatter.

All of the files build just fine, the problem is I cannot link to the regular contact page, as the alias overwrites the [@_lookup_by_path hash](https://github.com/middleman/middleman/blob/7bfacd565ae65574c397cb663a9db81a5cf1f25d/middleman-core/lib/middleman-core/sitemap/store.rb#L220).

Any ideas as to how I can make this work?

**Comment by jagthedrummer** [comment]
What happens when you do `<%= link_to "Contact", '/contact' %>` and/or `<%= link_to "Contact", '/contact.html' %>`?

**Comment by Tuckie** [comment]
I'm just going to handle these odd cases with a 301 in apache -- thanks!
