### ISSUE TITLE
Tag a version

### ISSUE THREAD

**Issue by philsturgeon** [Octo-Labs/middleman-alias#12]
Hey!

For me to use this comfortably, I'd really appreciate you tagging a version. Even 0.1.0 would be handy :)

**Comment by vietqhoang** [comment]
+1

**Comment by jagthedrummer** [comment]
I just tagged the current state of `master` as `0.0.13`. Is that what you're asking for?

**Comment by vietqhoang** [comment]
Yep. That'll work. Thanks!

**Comment by philsturgeon** [comment]
Perfect! Thank you.

--
Phil Sturgeon

**Comment by jagthedrummer** [comment]
No problem.
