### ISSUE TITLE
Doesn't work with middleman >= 3.3.0

### ISSUE THREAD

**Issue by RobertDeRose** [Octo-Labs/middleman-alias#15]
/middleman-alias-0.0.16/lib/middleman-alias/alias-resource.rb:46:in `raw_data': undefined method`raw_data' for nil:NilClass (NoMethodError)
    from /middleman-core-3.3.8/lib/middleman-core/core_extensions/front_matter.rb:77:in `data'
    from /middleman-alias-0.0.16/lib/middleman-alias/extension.rb:12:in`block in manipulate_resource_list'
    from /middleman-alias-0.0.16/lib/middleman-alias/extension.rb:11:in `each'

I've been trying to figure out what the issue is, but I've yet to figure out how `@alias_resource` get set in the `initialize` method

**Comment by rmm5t** [comment]
The gemspec certainly  isn't yet compatible with middleman 4.x, but I'm currently using middleman-alias v0.0.16 with middleman v3.4.1 just fine. Is there a particular use-case that you're using that might be triggering this?

**Comment by RobertDeRose** [comment]
Honestly, I don't think so. Just tried making updating middleman to 3.4.1 and that's the error I get.

**Comment by jesper-dk** [comment]
I can confirm that I can't get middleman-alias to work with Middleman 4.1.9. I added Middleman-Alias to my Gemfile, and ran Bundle Install. It then fails because the dependencies are too far apart:

    Bundler could not find compatible versions for gem "middleman-core":
    In Gemfile:
       middleman (>= 4.1.9, ~> 4.1) was resolved to 4.1.9, which depends on
         middleman-core (= 4.1.9)
       middleman-alias (~> 0.0.16) was resolved to 0.0.16, which depends on
        middleman-core (~> 3.2)

I'm certainly no Ruby programmer, but it seems to me that a relatively smaller amount of work on updating the Gemspec and testing this on Middleman 4 could ensure this lovely tool continues to work. Any chance for a version bump for Middleman 4? :)

**Comment by balinterdi** [comment]
That's exactly what I did in [my fork](https://github.com/balinterdi/middleman-alias), I bumped the middleman-core dependency to 4.2 and up.

However, it still doesn't work for me as I get the following error when running `middleman build --verbose`:

> <html><head></head><body><h1>File Not Found</h1><p>&#x2F;2016&#x2F;11&#x2F;29&#x2F;two-way-symmetric-relationships-in-ember-with-jsonapi-part-2&#x2F;index.html</p></body></html>

while I have the following in the new page's frontmatter:

> alias : /2016/11/29/two-way-symmetric-relationships-in-ember-with-jsonapi-part-2.html

I tried to manually create an empty page for the aliased page, to no avail.

**Comment by balinterdi** [comment]
I dug down a bit more and found that the page that should be redirected to the new one is not created and that's what I get the above error both during build and from the (middleman) server.

So my fork, which simple updated the middleman dependency to 4 does not seem to work. :(

I'd still like to help to get this solved but does not know enough of Middleman (4's) internal page rendering structure to attack this.

**Comment by bc-AlyssNoland** [comment]
@balinterdi Take a look at https://github.com/mzumi/middleman-alias from @mzumi. It seems to be working well for me.

**Comment by balinterdi** [comment]
@bc-AlyssNoland Thank you for the tip.

I now had some time to investigate and found the following.

The simple case works so if I want to redirect `emberjs-book` to `rock-and-roll-with-emberjs` it's enough to write `alias: emberjs-book/` in the frontmatter of `rock-and-roll-with-emberjs`.

However, if I want to redirect `/2016/11/29/two-way-symmetric-relationships-in-ember-with-jsonapi-part-2.html` to `/blog/two-way-symmetric-relationships-in-ember-with-jsonapi-part-2` and I write `alias: /2016/11/29/two-way-symmetric-relationships-in-ember-with-jsonapi-part-2.html` in the frontmatter of that source, I get the following error:

    error  /2016/11/29/two-way-symmetric-relationships-in-ember-with-jsonapi-part-2/index.html
    <html><head></head><body><h1>File Not Found</h1><p>&#x2F;2016&#x2F;11&#x2F;29&#x2F;two-way-symmetric-relationships-in-ember-with-jsonapi-part-2&#x2F;index.html</p></body></html>

**Comment by jagthedrummer** [comment]
Hey everybody, sorry for the late reply here. I think this should have been resolved last April with https://github.com/Octo-Labs/middleman-alias/pull/18 and the release of `0.0.17`.

**Comment by balinterdi** [comment]
Thank you, Jeremy. I ended up using the redirection capabilities of the deployment platform (Surge) but it might be interesting to have the solution baked into the site itself.
