### ISSUE TITLE
Redirects aren't relative

### ISSUE THREAD

**Issue by sman591** [Octo-Labs/middleman-alias#7]
During development, the entire site is previewed at root (http://localhost:4567/...), so absolute paths in redirects work just fine.

However, in production, this isn't always the case - the built site could be nested deeper than the root path, such as http://localhost:4567/**docs/**...)

Example: A redirect from `/abc/` to `/abc/newest/` works fine locally, but if in production it wasn't at the root, it would redirect from `/docs/abc/` to `/abc/newest/` instead of the desired `/docs/abc/newest`.

What's the best way to approach/fix this? Could the redirects be re-implemented with relative paths by default, unless specifically specified with a leading `/` ?

**Comment by sman591** [comment]
Fixed in #10

**Comment by jagthedrummer** [comment]
#10 is now merged.
